"""Pure graph execution contracts and runner."""

from dr_dspy.graph.execution import RunNode, execute_graph
from dr_dspy.graph.hashing import (
    GRAPH_DIGEST_LENGTH,
    canonical_graph_payload,
    graph_digest,
)
from dr_dspy.graph.models import (
    BindingRef,
    BindingSource,
    FieldRole,
    FieldSpec,
    FieldType,
    GraphExecutionError,
    GraphRunResult,
    GraphRunStatus,
    GraphSpec,
    GraphValidationError,
    InputResolutionError,
    NodeConfig,
    NodeError,
    NodeExecutionError,
    NodeOp,
    NodeOutcome,
    NodeOutcomeStatus,
    NodeOutput,
    NodeSpec,
    TerminalError,
)

__all__ = [
    "GRAPH_DIGEST_LENGTH",
    "BindingRef",
    "BindingSource",
    "FieldRole",
    "FieldSpec",
    "FieldType",
    "GraphExecutionError",
    "GraphRunResult",
    "GraphRunStatus",
    "GraphSpec",
    "GraphValidationError",
    "InputResolutionError",
    "NodeConfig",
    "NodeError",
    "NodeExecutionError",
    "NodeOp",
    "NodeOutcome",
    "NodeOutcomeStatus",
    "NodeOutput",
    "NodeSpec",
    "RunNode",
    "TerminalError",
    "canonical_graph_payload",
    "execute_graph",
    "graph_digest",
]
