import asyncio

from dspy.dsp.utils.settings import settings
from dspy.predict.multi_chain_comparison import MultiChainComparison
from dspy.primitives.prediction import Prediction
from dspy.signatures.field import InputField, OutputField
from dspy.signatures.signature import Signature
from dspy.task_spec.bridge import task_spec_from_signature
from dspy.utils.dummies import DummyLM


class BasicQA(Signature):
    """Answer questions with short factoid answers."""

    question = InputField()
    answer = OutputField(desc="often between 1 and 5 words")


# Example completions generated by a model for reference
completions = [
    Prediction(
        rationale="I recall that during clear days, the sky often appears this color.",
        answer="blue",
    ),
    Prediction(
        rationale="Based on common knowledge, I believe the sky is typically seen as this color.",
        answer="green",
    ),
    Prediction(
        rationale="From images and depictions in media, the sky is frequently represented with this hue.",
        answer="blue",
    ),
]


def test_basic_example():
    # Pass signature to MultiChainComparison module
    compare_answers = MultiChainComparison(task_spec_from_signature(BasicQA))

    # Call the MultiChainComparison on the completions
    question = "What is the color of the sky?"
    lm = DummyLM([{"rationale": "my rationale", "answer": "blue"}])
    settings.configure(lm=lm)
    final_pred = asyncio.run(compare_answers(completions, question=question))

    assert final_pred.rationale == "my rationale"
    assert final_pred.answer == "blue"
