"""Database schema contracts for the v1 eval platform."""

from dr_dspy.db.schema import (
    BATCH_SUBMIT_ITEMS_TABLE,
    BATCH_SUBMIT_OPERATIONS_TABLE,
    EXPERIMENTS_TABLE,
    GENERATION_RUNS_TABLE,
    NODE_ATTEMPTS_TABLE,
    PREDICTION_PROJECTION_TABLE,
    PREDICTION_SPECS_TABLE,
    SCORE_ATTEMPTS_TABLE,
    V1_TABLE_NAMES,
    batch_submit_items,
    batch_submit_operations,
    experiments,
    generation_runs,
    metadata,
    node_attempts,
    prediction_projection,
    prediction_specs,
    score_attempts,
    v1_tables,
)

__all__ = [
    "BATCH_SUBMIT_ITEMS_TABLE",
    "BATCH_SUBMIT_OPERATIONS_TABLE",
    "EXPERIMENTS_TABLE",
    "GENERATION_RUNS_TABLE",
    "NODE_ATTEMPTS_TABLE",
    "PREDICTION_PROJECTION_TABLE",
    "PREDICTION_SPECS_TABLE",
    "SCORE_ATTEMPTS_TABLE",
    "V1_TABLE_NAMES",
    "batch_submit_items",
    "batch_submit_operations",
    "experiments",
    "generation_runs",
    "metadata",
    "node_attempts",
    "prediction_projection",
    "prediction_specs",
    "score_attempts",
    "v1_tables",
]
